- BUGS.md
- TODO.md
- managers/user.py
- templates/email/welcome.html
Closes #39 
For the moment, set a default `background_tasks` to `None`, then test for that when registering. This allows us to not send emails when creating users from the CLI (where BackgroundTasks would be invalid anyway, and it's usually the superuser or for testing.)
> Fix Bug when creating user from CLI

- api-admin
- commands/custom.py
- commands/dev.py
- commands/user.py
- config/helpers.py
- poetry.lock
- pyproject.toml
`Typer` is a more advanced CLI library based on `click`, which we already use.
I have resisted migrating before since Typer does not support async functions, but I believe we can work around that.
> Migrate to Typer for the CLI

- .github/workflows/tests.yml
Disable the Codacy coverage upload.
This fails on forks and occasionally can be dodgy getting the project_key even on the main.
We still have the main code-cov service working
> Disable the Codacy coverage upload.

- api-admin
- commands/docs.py
- docs/development/documentation.md
- pyproject.toml
The online documentation requires a valid and recent `openapi.json` file to generate the 'Interactive API Docs` page. 
This PR adds a command to the CLI to do this and some `Poe` tasks to automate it. We also update the Web docs to reflect these new commands.
> Fix missing openapi schema for Docs

- README.md
- docs/CNAME
- mkdocs.yml
Serve the docs from a custom domain `https://api-template.seapagan.net`. Still hosted from GitHub though
> add custom domain for docs

- README.md
- docs/contributing.md
- docs/index.md
- pyproject.toml
Refactor the project versions to start at `0.4.0`
The original template was written for my own use and probably promoted to V1.0.0 before it should have been, and there have been many updates and fixes since then.
I will keep the old releases available for those who wish to use them (for a short time). It's better to do this now before more users need to update their projects to future versions.
All releases from now on will also contain a Git patch to upgrade from the previous version. This will be in the form of a `.patch` file which can be applied to their project using the `git apply` command. This will be documented in the release notes.
> Refactor versioning

- docs/index.md
- mkdocs.yml
- poetry.lock
- pyproject.toml
Take the latest release tag and display this in the online documentation. 
I quickly wrote an MkDocs plugin to do this: [mkdocs-latest-git-tag-plugin](https://seapagan.github.io/mkdocs-latest-git-tag-plugin/).
> Add release version to docs

- app/main.py
- pyproject.toml
The FastAPI startup event is deprecated, it is now recommended to use the 'lifespan' functionality instead
> Migrate startup to lifespan

- app/api_admin.py
- app/commands/custom.py
- app/config/helpers.py
- app/config/settings.py
- app/main.py
- app/resources/home.py
- docs/customization/meta.md
- docs/development/documentation.md
- docs/development/local.md
- docs/usage/add-user.md
- docs/usage/configuration/database.md
- docs/usage/configuration/setup.md
- docs/usage/user-control.md
- pyproject.toml
- tests/unit/test_config_helpers.py
[`NOTE: This does NOT make this into a package that can be pushed to PyPI, in fact, it specifically has the "Private :: Do Not Upload" classifier`]
Avoids a  new Poetry warning.
Poetry devs stubbornly believe that it's only used for packages despite complaints. The newest version gives a very obtrusive error-like warning if a package is not defined and '--no-root' is not specified.
This PR adds a package config to the API, which is installed in editable mode when running `poetry install`. This removes the warning and allows us to make the `api-admin` command an actual command instead of a script, which can be run from any location as long as the virtual env is active.
This is a `breaking change` for the CLI usage, but otherwise, it will be transparent to the API
> make the API an installable package and CLI command

- app/commands/custom.py
- tests/cli/test_cli_custom_command.py
- tests/unit/test_database.py
Merging early to fix test failures caused by misuse of `pyfakefs` library
> Continue testing on the `api-admin custom` CLI command

- TODO.md
- app/config/settings.py
- app/resources/routes.py
- docs/usage/configuration/environment.md
- tests/unit/test_validation.py
set the `API_ROOT` variable in the `.env`file to enable this. If unset then it will be ignored
> Allow setting a custom API root path e.g. "/api/v1" to prepend to all routes

- .github/workflows/tests.yml
- README.md
- docs/important.md
- docs/usage/installation.md
> Update the coverage action

- pyproject.toml
- requirements-dev.txt
- requirements.txt
- tests/conftest.py
- uv.lock
the `httpx`library (used for the test runner) has deprecated the old way the app is passed, which raises a deprecation warning in the tests. We had originally pinned an older version until `Starlette` changed it's code, that is released now too.
> fix deprecation warning in tests due to httpx

- Dockerfile
- LICENSE.txt
- app/config/metadata.py
- docker-compose.yml
- docs/development/docker.md
- pyproject.toml
Use Python version `3.13` and PostgreSQL version `17.3` in the docker configs. 
This is a potential breaking change if you have an existing docker database, since any existing data is not compatible with postgres 17. You have 3 options:
1) delete the docker volume `api-db-data` and just start again. This is fine if you are only using docker for testing.
2) change the `docker-compose.yml` to use the previous version of `15.6-bullseye` instead. This is on line **25** (as of this PR anyway)
3) log into the docker instance and migrate the data to version 17. There are several guides for this if you search.
> use latest versions of postgresql and python in docker

- TODO.md
- app/commands/user.py
- pyproject.toml
- requirements-dev.txt
- requirements.txt
- uv.lock
`passlib` is basically abandoned, `libpass` is a maintained and improved fork. 
I was going to just implement the hashing manually using `bcrypt` directly but this is probably more backward-compatible as only the import changes and not the code. 
Allows updating to the latest version of `bcrypt` too
> migrate from `passlib` to `libpass`

- pyproject.toml
- requirements-dev.txt
- uv.lock
switched to a fork of this plugin (until the relevant PR gets merged)
> fix deprecation warning in docs build d/t mkdocs swagger plugin

- tests/cli/test_cli_custom_command.py
Finally get full test coverage on the 2 missing blocks:
1. in the `custom metadata` CLI command, the path where the `pyproject.toml` cant be updated wasn't tested
2. the import test for `app.config.metadata` in the same command
Fair warning, the test for number 2 is a bit hacky :grin:
> get test coverage up to 100% by testing the last uncovered blocks

- app/managers/api_key.py
- app/resources/api_key.py
- docs/usage/api-keys.md
- tests/integration/test_api_key_routes.py
- tests/unit/test_api_key_auth.py
- tests/unit/test_api_key_manager.py
Add 3 more routes that allow an admin to list/edit and delete the API keys for a specific user.
> Allow Admin users to list/edit/delete other users API keys

- README.md
- app/commands/user.py
- app/main.py
- app/managers/user.py
- app/resources/user.py
- app/schemas/request/user.py
- docs/project-organization.md
- docs/usage/user-control.md
- pyproject.toml
- requirements-dev.txt
- requirements.txt
- tests/cli/test_cli_user_command.py
- tests/integration/test_user_routes.py
- tests/unit/test_user_manager.py
- uv.lock
add a `/search` endpoint to search the Users by email, first or last names. Also adds a `user search` command to the CLI.
> add user search endpoint with pagination and CLI command for same

- .gitignore
- README.md
- app/commands/db.py
- docs/important.md
- docs/index.md
- docs/usage/user-control.md
- tests/cli/test_cli_db_command.py
add a CLI command `db populate` which creates 5 test users (1 admin, 4 standard users) for testing and development purposes. All users will have the same password of `Password123!`
You can also add a `--count` flag to specify exactly how many users to create. In this case, it will create 1 admin for every 5-user group, up to a maximum of 3 users.
> CLI: add a command to populate test users into the database

- .gitignore
- README.md
- app/commands/db.py
- docs/index.md
- docs/usage/user-control.md
- tests/cli/test_cli_db_seed.py
Allow seeding the database with data (say your admin users and dev/test team) simply using a seed file in CSV format.
You can specify a file, or it will default to `users.seed` in the current folder.
> [!IMPORTANT]
>
> This seed file should obviously NOT be checked into source control if it is public!! The project `.gitignore` contains the default `users.seed` file already.
Example file:
```csv
email,password,first_name,last_name,role
admin@example.com,AdminPassword123!,Admin,User,admin
john.doe@example.com,SecurePass456!,John,Doe,user
jane.smith@example.com,StrongPass789!,Jane,Smith,user
tech.lead@example.com,LeadPass321!,Tech,Lead,admin
support@example.com,SupportPass987!,Support,Team,user
```
As seen above, the first row is compulsory and lists the columns, except the role column is …
> add a 'seed' command to the 'db' group in the CLI

- pyproject.toml
- requirements-dev.txt
- uv.lock
Use my own fork for the `mkdocs-swagger-ui-tag`	mkdocs plugin. This fixes the deprecation warning, and also allows to use the 'defaultModelsExpandDepth' tag without warnings.
> replace the mkdocs swagger plugin with my own fork

- requirements-dev.txt
- requirements.txt
- uv.lock
several potential security issues flagged by dependabot, so updating the affected libraries as required.
> update libraries as required to fix security alerts

- app/database/db.py
- tests/unit/test_database.py
Add a second database dependency that will NOT call the explicit `.begin()` on the session, so the session will only be opened when first accessed and should allow multiple database calls in the same route.
Should allow closing #768 
In future this may be the default functionality but for now lets leave the auto-commit dependency as default.
> feat: add manual database session handling with rollback on exception
